### ISSUE TITLE
Allow apex local network name instead of ip

### ISSUE THREAD

**Issue by brettonw** [itchannel/apex-ha#10]
I haven't looked at why this fails, but the Apex registers itself on the local network as "apex". In my configuration, I can access the device using "http://apex.local".

When setting up the integration, I was not able to use the name, and had to use the IP. This is fine, but if the DHCP reservation ever changes my integration will drop. I'd prefer to use the registered name "apex.local".

**Comment by itchannel** [comment]
I'll have to look into this as don't know if the .local dns namespace would be resolvable inside the HA container. I'll have a play on my dev instance.

**Comment by brettonw** [comment]
I run HA in a container and set the resolver to my local router in the docker compose file. I refer to other local integrations using names, so I was surprised this one failed.

**Comment by itchannel** [comment]
Ok if that's the case then I'll see what I can do 👍

**Comment by itchannel** [comment]
![image](https://user-images.githubusercontent.com/5840973/186536052-fb94d88d-7566-4b69-a868-878e2285e132.png)

Works for me OK using the DNS name "apex.local"

**Comment by brettonw** [comment]
I tried again and it still doesn't work for me. I'll see if I can track down why.

**Comment by brettonw** [comment]
I suspect this is a local network issue for me. Looking at the code there is no reason this shouldn't work.

**Comment by brettonw** [comment]
How do you run HA? In a container?

**Comment by itchannel** [comment]
My main instance is HA OS and my dev instance is a container in docker.
