### ISSUE TITLE
Temperature is unitless in rest interface

### ISSUE THREAD

**Issue by brettonw** [itchannel/apex-ha#12]
The default conversion in the integration is to use degrees Celsius, but my Apex is configured for degrees Fahrenheit. Is the Apex configuration available through the rest interface to determine what the unit should be?

**Comment by itchannel** [comment]
I can add in an option for units to be set manually but I will see if the controller exposes the unit set as well.

**Comment by itchannel** [comment]
1.07 now grabs the configuration from the device and currently just sets the temperature to Celsius or Fahrenheit depending on your system config. Couldn't find any other inputs that used measurements on my system.

**Comment by itchannel** [comment]
Closing issue as 1.07+ now pulls the temp config from the controller.
