### ISSUE TITLE
Entity naming is terse

### ISSUE THREAD

**Issue by brettonw** [itchannel/apex-ha#14]
Apex has very terse names that are often not descriptive enough. When importing them into HA, prefix the apex inputs/outputs with "apex_" to avoid polluting the HA namespace with these bad Apex names. For instance, Apex "Sw_1" is simply imported into HA as "switch.sw_1".  It would be much easier to find the entities if it was "switch.apex_sw_1".

**Comment by itchannel** [comment]
Agreed the naming scheme needs changing to be in line with HA best practice so I will change it in the next release to apex_sensorname

**Comment by itchannel** [comment]
Fixed in 1.07
