### ISSUE TITLE
Rebooting Apex loses HA connection permanently

### ISSUE THREAD

**Issue by brettonw** [itchannel/apex-ha#20]
I updated the software in my Apex, and had to reboot it in the process. The HA connection was lost, and at first I thought Neptune had changed their rest API interface and broken the integration. The only way I could get it back was to remove the integration and re-add it. I subsequently rebooted the Apex again, and had the same problem. Does the login cookie need to be refreshed if an API call fails?

**Comment by itchannel** [comment]
Reloading the integration also works but yeah I forgot to check for an expired session cookie. Will add a simple status_code check later today.

**Comment by itchannel** [comment]
1.09 pre release should fix this issue I've added a check for a 401 status code and will retry obtaining a new cookie up to 3 times before giving up. (Had to add the 3 retries as at least my controller can be a little finicky with logging in)

**Comment by brettonw** [comment]
Confirmed Fixed.
