### ISSUE TITLE
pH is not technically a unit

### ISSUE THREAD

**Issue by brettonw** [itchannel/apex-ha#26]
Perhaps if you set sensors to state class measurement, you can drop the "pH" on the unit.

**Comment by brettonw** [comment]
I looked at setting the state_class to measurement, but I think that will only apply to a SensorEntity. You set the unit of measurement dynamically from the config, so it might be challenging to convert to a SensorEntity (which has unit_of_measurement marked as final). As a workaround, I set the measurement to " ". The forum has a lot of discussion as to why that's not a desirable solution.

**Comment by itchannel** [comment]
Merged in commit from @brettonw in 1.09
