### ISSUE TITLE
FEATURE - Poll frequency

### ISSUE THREAD

**Issue by behold81** [itchannel/apex-ha#3]
Firstly, I was just trying to work out this and you have just done this for me. you are awesome. 

It would be great if you could control the poll interval if possible. some might want it only every x mins to remove load from the poll. I assume switches are not an issue as it calls an API to enact a switch. 

Maybe its not suitible but I thought I would float the idea.

**Comment by itchannel** [comment]
Good idea now available in the latest release 1.05. 

Update interval (In Minutes) can be set in options

**Comment by behold81** [comment]
![image](https://user-images.githubusercontent.com/24306233/185081668-2086f81c-9f25-41de-b178-f03a23b03ada.png)

There is not description on the configure button for the option. I assume it is on the initial configure but not this screen.

**Comment by itchannel** [comment]
It is on mine. Try doing CTRL R in your browser as probably a cache issue. 

![image](https://user-images.githubusercontent.com/5840973/185082954-a19c9e94-7c30-4ad7-85fd-3e18f69ddbb6.png)

**Comment by behold81** [comment]
It finally caught up. I thought I had done that but apparently not. Ill go sit back in my box!!

**Comment by mlmhhomeauto** [comment]
It is great to have the option of the poll interval, but for my usage it would be an improvement to have the option to be in seconds vs minutes.  Using the smaller measurement still allows for minutes as in setting the poll interval to 300 sec would equal 5 minutes.

**Comment by behold81** [comment]
Its a fair point but be aware polling too frequently will impact the apex brain and cause it to slow and not work.

**Comment by itchannel** [comment]
@mlmhhomeauto I did start with seconds when I was programming it but my Apex was very unstable polling quicker than a minute. The newer version might be more stable but the older models just aren't very powerful from my findings. 

Happy to change it to seconds if people would prefer it just put minutes to avoid people complaining when it doesn't poll every 5 seconds 👍

**Comment by behold81** [comment]
Will it accept 0.25 mins? (So 15 seconds?)

**Comment by itchannel** [comment]
Will change it to seconds in the next release. Will have to be a disclaimer if anyone has it set in minutes though on this release 👍
