### ISSUE TITLE
REQ: Feed mode

### ISSUE THREAD

**Issue by Jbb421** [itchannel/apex-ha#38]
Sorry if it's already there and I've just not seen it, but it would be absolutely awesome if the feed mode switches were available as a switch, to beable make a feedmode widget with HA

Thanks for this addon, and all the hard work you've put into it!

**Comment by brettonw** [comment]
I used Home Assistant to implement a more robust feeding time automation that integrates various sensors and timers, and exposes that automation out to HomeKit/Siri. “Aquarium Feeding Time” stops all the pumps for 15 minutes, including the skimmer, ATO, and dosing. After the main return comes back on, it waits 5 minutes to turn on everything except the skimmer. Then it waits for the sump water level to drop below a threshold before starting the skimmer (so it won’t just overflow the cup).

**Comment by Jbb421** [comment]
Would you mind sharing thar configuration with me? Thank you for the reply!

**Comment by itchannel** [comment]
Simple feed cycle switches and countdown sensor added in 1.13 :)
