### ISSUE TITLE
FEATURE - Auto Mode

### ISSUE THREAD

**Issue by behold81** [itchannel/apex-ha#4]
Is there a way to turn an item to Auto not ON. its almost like we need both options. not sure how that could work. 

Sorry for the barrage of features. I'm excited!

**Comment by itchannel** [comment]
So unfortunately HA doesn't currently support 3 way switches from what I can see. So I've added in a new service called "set_output" you can call this with the given output DID (Found under switch attributes) and select from OFF/ON/AUTO. Can be used with a hacs custom button or in an automation.

**Comment by behold81** [comment]
That's cool. so at least automation could be used or a helper switch to set auto modes. I wonder if there is a way to mimic a 3 way switch some how. Ill see if I can find an option and let you know if I find something. but for now an awesome workaround. I will test it later today.

**Comment by itchannel** [comment]
One option is to map it to a slider with the 3 options but requires a custom lovelace widget like this https://github.com/thomasloven/lovelace-slider-entity-row

**Comment by behold81** [comment]
Thats cool. Ill look in to that. could be very usable. Thanks

**Comment by itchannel** [comment]
Closing issue as added in 1.05 (Service call allows AUTO toggling)
