### ISSUE TITLE
Polling Rate?

### ISSUE THREAD

**Issue by ylnest2018** [itchannel/apex-ha#48]
Hi not sure if this is an issue or just by design, wondering if the polling rate is set to 60seconds or similar.

Seems whenever I send a command from HA to the Apex it'll send it in 15seconds or less however when changing on the apex side it takes 55-60 seconds before it will update in HA.

If so, wondering if this can be altered in any way?

**Comment by ylnest2018** [comment]
If only I read past the first few lines, I see you can modify this I will look for the setting

**Comment by ylnest2018** [comment]
Adjusted polling rate in the integration, thank you

**Comment by brettonw** [comment]
Out of curiosity, what did you set it to?

**Comment by ylnest2018** [comment]
I’m still cycling my tank so can afford to risk a fail, but I have set it to 10secondsKind Regards,Leo Di Bartolo0426 266 165On 10 Jul 2024, at 12:17 PM, Bretton Wade ***@***.***> wrote:﻿
Out of curiosity, what did you set it to?
