### ISSUE TITLE
FEATURE - Dosing Containers

### ISSUE THREAD

**Issue by behold81** [itchannel/apex-ha#5]
I have the wiring mod on my DOS units. and it would be awesome to use HA to alert when my containers are getting low. 

,{"status":["OFF","","OK","1900","0"],"name":"SPARE","gid":"doser_8","type":"dos","ID":31,"did":"8_1"}
,{"status":["TBL","","OK","1500","898"],"name":"TRITON_1","gid":"doser_8","type":"dos","ID":32,"did":"8_2"}
,{"status":["TBL","","OK","1500","863"],"name":"TRITON_2","gid":"doser_9","type":"dos","ID":33,"did":"9_1"}
,{"status":["TBL","","OK","2200","1644"],"name":"TRITON_3a_3b","gid":"doser_9","type":"dos","ID":34,"did":"9_2"}

They appear in the json but not in the entities. I assume as they are a type:dos. 

Addition of these would be very useful.

**Comment by itchannel** [comment]
Could you provide me a copy of your json from either debug or the /rest/status file. I don't have dosing on my apex only ATK so need the full schema and I can add it in.

**Comment by behold81** [comment]
[Apex.txt](https://github.com/itchannel/apex-ha/files/9358086/Apex.txt)

As requested. Plenty of items. I am also going to be adding some IOTA Devices soon. so Ill let you know if that pulls another type.

**Comment by itchannel** [comment]
Thanks for the json. Wow you have a lot of devices compared to my setup. 

I can see some extra statuses for some of your outputs I need to add. Just wondering does the switches show for the DOS units and the other bits in HA? My code should of added them but will have the wrong statuses until I add them.

**Comment by behold81** [comment]
Yeah I have a few items! 

So the dos units do not show at all. It looks like it has both the unit and containers in one. The numbers in Litres being size of container and how much is left in it. 

There return variables are using the 0-10v ports on the apex and may show On and a % similar to a WAV 

as to the other items. I have 1 of my power bars being the newer EB632 so it has W and amps. 

There are only a few items I don’t have. 

I will be interested to see how the lights show up when I add them through the IOTA connection. That could be interesting 

either way. For now I just want info not control(although in the future it will be useful)  so happy to test,break and retest anything to help you make this better.

**Comment by itchannel** [comment]
I could add the DOS type as a sensor which shows the current level and then the capacity can just be an attribute for that sensor. I'm surprised it hasn't added the ON/OFF switches for the DOS units in HA as my code just loops through the whole output array and adds every entity. 

Will have a look later and see what I can add, might need to make a mock controller for testing :)

**Comment by behold81** [comment]
That would work. Current level is all that is really important. Unless someone makes a level card! 

I’m not sure I have ever manually turned on the DOS.

**Comment by itchannel** [comment]
Current level is now shown as a sensor for DOS. So closing this issue for now :)

**Comment by behold81** [comment]
![5755f457-eed2-4911-900b-c0146c6d5e5f](https://user-images.githubusercontent.com/24306233/186853968-336ce37c-5a30-4f45-8aa9-6d596c4638bd.jpg)
Bit dirty screen but here is some image of Apex in HA Dashboard for you.

**Comment by itchannel** [comment]
Dashboard looks good 👍
